### ISSUE TITLE
This message will never be used

### ISSUE THREAD

**Issue by amolholani** [Santosh2740/quizzical-trade-9516#9]
https://github.com/Santosh2740/quizzical-trade-9516/blob/51e5cef7f6ac894da1bd0078bb52c6f139726277/Human-Resource-management-system/src/com/masai/dao/DepartmentDaoImpl.java#L20

**Comment by Santosh2740** [comment]
Without a declaration of message how to override a function which is written in forLoop, line number 34 onward.
